# Generated by Django 4.1.3 on 2022-12-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blankmeta",
            name="timings",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
