# Generated by Django 4.1.3 on 2022-12-10 10:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="method",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
