# Generated by Django 4.1.3 on 2022-12-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_rename_date_recipe_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blank",
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
    ]
